pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '613591981591'
        ECR_REPO = 'myapp'
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('AWS Identity Check') {
            steps {
                sh '''
                    aws sts get-caller-identity
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Project-4-Docker-ECR-Jenkins-Lambda') {
                    sh '''
                        docker build -t ${ECR_REPO}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${ECR_REGISTRY}
                '''
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                    docker tag ${ECR_REPO}:${IMAGE_TAG} \
                    ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                    docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Verify ECR Image') {
            steps {
                sh '''
                    aws ecr describe-images \
                    --repository-name ${ECR_REPO} \
                    --image-ids imageTag=${IMAGE_TAG} \
                    --region ${AWS_REGION}
                '''
            }
        }
    }

    post {
        success {
            echo "Docker image successfully pushed to Amazon ECR!"
            echo "Image: ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
        }

        failure {
            echo "Pipeline failed. Check the console output."
        }
    }
}
